version: '3.4'

services:
  jenkins:
    restart: unless-stopped
    build:
      context: ./image
    # image: jenkins/jenkins:lts
    volumes:
      - ${PWD}/work/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    network_mode: bridge
